---
namespace: imp1sh
name: ansible_openwrt
version: 0.3.1
readme: README.md
authors:
  - Jochen Demmer <jochen@libcom.de>
description: ansible_openwrt is a full featured openwrt collection. It relies on python so you need enough disk space in order to be able to use it.
license_file: 'LICENSE'
tags: [openwrt, lede, dhcp, dnsmasq, dropbear, ssh, firewall, network, packages, restic, backup, services, system, wifi, wireless, wireguard, vpn, sqm, imagebuilder, wireguard]
dependencies: {}
repository: https://github.com/imp1sh/ansible_openwrt
documentation: https://wiki.junicast.de/de/junicast/docs/AnsibleOpenWrtCollection
homepage: https://github.com/imp1sh/ansible_openwrt
issues: https://github.com/imp1sh/ansible_openwrt/issues
