---
# tasks file for ansible_openwrtdhcp
- name: merge dhcp group pools
  include_tasks: merge.yml
  when: openwrt_dhcp_poolsgroup is defined
- name: Install dhcp config
  template:
    src: dhcp.jinja2
    dest: "{{ openwrt_dhcp_deployroot }}{{ openwrt_dhcp_deploypath }}/{{ openwrt_dhcp_deployfile }}"
    owner: root
    group: root
    mode: 0600
  notify: restart dnsmasq

