---
# Prepare first phase
- name: Merge packages_remove from all groups this host is a member of
  ansible.builtin.set_fact:
    openwrt_packages_removemergedgroup: "{{ openwrt_packages_removegroup.keys() | list | intersect(group_names) | map('extract', openwrt_packages_removegroup) | list | flatten }}"
  when: openwrt_packages_removegroup is defined
- name: Set seperator if imagebuilder
  ansible.builtin.set_fact:
    openwrt_packages_separator: ' '
  when: openwrt_packages_runimagebuilder | default(false)
- name: Set separator if not imagebuilder
  ansible.builtin.set_fact:
    openwrt_packages_separator: ','
  when: not openwrt_packages_runimagebuilder | default(false)
# Prepare second phase. There are 8 possibilities on how role, group based or host based vars can be set
# Variant H is where none is set so no action for this
- name: Variant A - Merge role/host/group
  ansible.builtin.set_fact:
    openwrt_packages_remove: "{{ openwrt_packages_removehost + openwrt_packages_removemergedgroup + openwrt_packages_removerole }}"
  when:
    - openwrt_packages_removemergedgroup is defined
    - openwrt_packages_removehost is defined
    - openwrt_packages_removerole is defined
- name: Variant B - Merge Group and Host
  ansible.builtin.set_fact:
    openwrt_packages_remove: "{{ openwrt_packages_removehost + openwrt_packages_removemergedgroup }}"
  when:
    - openwrt_packages_removemergedgroup is defined
    - openwrt_packages_removehost is defined
    - openwrt_packages_removerole is not defined
- name: Variant C - Merge Host and Role
  ansible.builtin.set_fact:
    openwrt_packages_remove: "{{ openwrt_packages_removehost + openwrt_packages_removerole }}"
  when:
    - openwrt_packages_removemergedgroup is not defined
    - openwrt_packages_removehost is defined
    - openwrt_packages_removerole is defined
- name: Variant D - Only host set
  ansible.builtin.set_fact:
    openwrt_packages_remove: "{{ openwrt_packages_removehost }}"
  when:
    - openwrt_packages_removemergedgroup is not defined
    - openwrt_packages_removehost is defined
    - openwrt_packages_removerole is not defined
- name: Variant E - Merge Group and Role
  ansible.builtin.set_fact:
    openwrt_packages_remove: "{{ openwrt_packages_removemergedgroup + openwrt_packages_removerole }}"
  when:
    - openwrt_packages_removemergedgroup is defined
    - openwrt_packages_removehost is not defined
    - openwrt_packages_removerole is defined
- name: Variant F - Only group set
  ansible.builtin.set_fact:
    openwrt_packages_remove: "{{ openwrt_packages_removemergedgroup }}"
  when:
    - openwrt_packages_removemergedgroup is defined
    - openwrt_packages_removehost is not defined
    - openwrt_packages_removerole is not defined
- name: Variant G - Only role set
  ansible.builtin.set_fact:
    openwrt_packages_remove: "{{ openwrt_packages_removerole }}"
  when:
    - openwrt_packages_removemergedgroup is not defined
    - openwrt_packages_removehost is not defined
    - openwrt_packages_removerole is defined
- name: Convert List to string
  ansible.builtin.set_fact:
    openwrt_packages_remove: "{{ openwrt_packages_remove | join(openwrt_packages_separator) }}"
  when: openwrt_packages_remove is defined
