---
- name: Uninstall packages
  community.general.opkg:
    name: "{{ openwrt_packages_remove }}"
    state: absent
  when:
    - openwrt_packages_remove is defined
    - not openwrt_packages_runimagebuilder | default(false)
