---
- name: Merge packagesinstall from all groups this host is a member of
  set_fact:
    openwrt_packagesinstallmergedgroup: "{{ openwrt_packagesinstallgroup.keys() | list | intersect(group_names) | map('extract', openwrt_packagesinstallgroup) | list | flatten }}"
  when: openwrt_packagesinstallgroup is defined
- name: Initialize unset installhost variable as empty list
  set_fact:
    openwrt_packagesinstallhost: []
  when: openwrt_packagesinstallhost is not defined
- name: Initialize unset installgroup variable as empty list
  set_fact:
    openwrt_packagesinstallgroup: []
  when: openwrt_packagesinstallgroup is not defined
- name: Cast from list to comma seperated string - Install
  set_fact:
    openwrt_packages_install: "{{ (openwrt_packagesinstallmergedgroup + openwrt_packagesinstallhost) | join (',') }}"
  when:
    #- openwrt_packagesinstallmergedgroup is defined
    # I don't understand why I once set this condition. I can always merge the lists..., can I not?
    - not openwrt_packages_runimagebuilder | default(false)
- name: Cast from list to space seperated string - Install Imagebuilder
  set_fact:
    openwrt_packages_install_imagebuilder: "{{ (openwrt_packagesinstallmergedgroup + openwrt_packagesinstallhost) | join (' ') }}"
  when:
    - openwrt_packages_runimagebuilder | default(false)
- name: Install packages
  opkg:
    name: "{{ openwrt_packages_install }}"
    state: present
    update_cache: yes
  when:
    - openwrt_packages_install is defined
    - not openwrt_packages_runimagebuilder | default(false)
