---
# tasks file for ansible_openwrtacme
- name: make sure deploypath is present
  ansible.builtin.file:
    path: "{{ openwrt_acme_deploypath }}"
    state: directory
- name: Install packages
  opkg:
    name: "acme,acme-dnsapi,luci-app-acme"
  when:
    not openwrt_acme_runimagebuilder | default(false)
- name: Setup acme config
  template:
    src: "acme.jinja2"
    dest: "{{ openwrt_acme_deploypath }}/{{ openwrt_acme_deployfile }}"
  notify: restart acme
