---
# tasks file for ansible_openwrtwireless
- name: Make sure wireless deploypath exists
  ansible.builtin.file:
    path: "{{ openwrt_wireless_deploypath }}"
    state: directory
- name: deploy wireless config
  ansible.builtin.template:
    src: "wireless.jinja2"
    dest: "{{ openwrt_wireless_deploypath }}/{{ openwrt_wireless_deployfile }}"
    mode: "0600"
  when: openwrt_wifi_devices is defined
  notify: restart wireless
