---
# tasks file for ansible_openwrtwireless
- name: deploy wireless config
  template:
    src: "wireless.jinja2"
    dest: "{{ openwrt_wireless_deploypath }}"
    mode: "0600"
  when: openwrt_wifi_devices is defined
  notify: restart wireless
