---
galaxy_info:
  role_name: ansible_openwrtacme
  author: Jochen Demmer
  description: Lets you manage acme letsencrypt certificates on OpenWrt
  company: libcom.de
  issue_tracker_url: https://github.com/imp1sh/ansible_openwrt/issues
  license: BSD-3-Clause
  min_ansible_version: "2.9"
  platforms:
    - name: OpenWRT
      versions:
        - "21.02"
        - "22.03"
  galaxy_tags: [openwrt, lede, letsencrypt, acme, certmanager]
dependencies:
  - role: imp1sh.ansible_openwrt.ansible_openwrtpackages
    vars:
      openwrt_packages_installrole:
        - acme
        - acme-acmesh-dnsapi
        - luci-app-acme
