---
galaxy_info:
  author: Jochen Demmer
  description: lets you manage acme letsencrypt certificates on OpenWrt
  company: libcom.de
  license: BSD-3-Clause
  min_ansible_version: 2.9
  platforms:
    - name: OpenWrt
      versions:
        - 21.02
        - 22.03
  galaxy_tags: [openwrt, lede, letsencrypt, acme, certmanager]
dependencies:
  - role: imp1sh.ansible_openwrt.ansible_openwrtpackages
    vars:
      openwrt_packages_installrole:
        - acme
        - acme-dnsapi
        - luci-app-acme
