---
# integrate installed packages into backup and consider for sysupgrade
- name: make sure sysupgrade.conf file exists
  ansible.builtin.file:
    path: "{{ openwrt_restic_deploypath_sysupgrade }}/{{ openwrt_restic_deployfile_sysupgrade }}"
    mode: '0644'
    state: touch
- name: add /etc/config/installed.packages to sysupgrade config
  ansible.builtin.lineinfile:
    path: "{{ openwrt_restic_deploypath_sysupgrade }}/{{ openwrt_restic_deployfile_sysupgrade }}"
    line: /etc/config/installed.packages
    regexp: /etc/config/installed.packages
    state: present
# deploy restic config and password
- name: deploy restic configuration
  ansible.builtin.template:
    src: restic.conf.jinja2
    dest: "{{ openwrt_restic_deploypath }}/{{ openwrt_restic_deployfile }}_{{ backupitem['name'] }}"
    mode: 0600
  when: openwrt_restic_backups is defined
  loop: "{{ openwrt_restic_backups }}"
  loop_control:
    loop_var: backupitem 
- name: deploy restic password file
  ansible.builtin.template:
    src: password.jinja2
    dest: "{{ openwrt_restic_deploypath_passwordfile }}/{{ openwrt_restic_deployfile_passwordfile }}_{{ backupitem['name'] }}"
    mode: 0600
  when: openwrt_restic_backups is defined
  loop: "{{ openwrt_restic_backups }}"
  loop_control:
    loop_var: backupitem 
