---
- name: make sure root user has ssh public key
  ansible.builtin.user:
    name: "root"
    generate_ssh_key: true
  register: rootuser
  when: backupitem['manage_ssh'] | default(false)
- name: provide root user's public key to destination machine
  ansible.posix.authorized_key:
    user: "{{ backupitem['sshkey_user'] }}"
    state: present
    key: "{{ rootuser['ssh_public_key'] }}"
  become: true
  become_user: root
  delegate_to: "{{ backupitem['targethost'] }}"
  when: backupitem['manage_ssh'] | default(false)
- name: make sure known_hosts file exists
  ansible.builtin.file:
    path: "{{ openwrt_restic_deploypath_knownhosts }}"
    state: "touch"
  when: backupitem['manage_ssh'] | default(false)
- name: install target hosts fingerprint to known hosts
  ansible.builtin.known_hosts:
    path: "/root/.ssh/known_hosts"
    key: "{{ lookup('pipe', '/usr/bin/ssh-keyscan -tecdsa ' + borgmatic_sshkey_targethost) }}"
    name: "{{ backupitem['targethost'] }}"
    state: present
  when: backupitem['manage_ssh'] | default(false)
