---
galaxy_info:
  role_name: ansible_openwrtwireguard
  author: Jochen Demmer
  description: Installs Wireguard VPN dependencies in OpenWrt
  company: libcom.de
  issue_tracker_url: https://github.com/imp1sh/ansible_openwrt/issues
  license: BSD-3-Clause
  min_ansible_version: "2.9"
  platforms:
    - name: OpenWRT
      versions:
        - "21.02"
        - "22.03"
  galaxy_tags: [openwrt, lede, wireguard, vpn, security]
dependencies:
  - role: imp1sh.ansible_openwrt.ansible_openwrtpackages
    vars:
      openwrt_packages_installrole:
        - wireguard-tools
        - kmod-wireguard
        - luci-app-wireguard
        - luci-proto-wireguard
