---
# defaults file for ansible_openwrtdhcp
openwrt_dhcp_dnsmasq_domainneeded: "1"
openwrt_dhcp_dnsmasq_boguspriv: "1"
openwrt_dhcp_dnsmasq_filterwin2k: "0"
openwrt_dhcp_dnsmasq_localise_queries: "1"
openwrt_dhcp_dnsmasq_rebind_protection: "1"
openwrt_dhcp_dnsmasq_rebind_localhost: "1"
openwrt_dhcp_dnsmasq_local: "/lan/"
openwrt_dhcp_dnsmasq_domain: "lan"
openwrt_dhcp_dnsmasq_expandhosts: "1"
openwrt_dhcp_dnsmasq_nonegcache: "0"
openwrt_dhcp_dnsmasq_authoritative: "1"
openwrt_dhcp_dnsmasq_readethers: "1"
openwrt_dhcp_dnsmasq_leasefile: "/tmp/dhcp.leases"
openwrt_dhcp_dnsmasq_resolvfile: "/tmp/resolv.conf.d/resolv.conf.auto"
openwrt_dhcp_dnsmasq_nonwildcard: "1"
openwrt_dhcp_dnsmasq_localservice: "1"
openwrt_dhcp_deployroot: "/"
openwrt_dhcp_deploypath: "etc/config/"
openwrt_dhcp_deployfile: "dhcp"
openwrt_dhcp_odhcpd_maindhcp: "0"
openwrt_dhcp_odhcpd_leasefile: "/tmp/hosts/odhcpd"
openwrt_dhcp_odhcpd_leasetrigger: "/usr/sbin/odhcpd-update"
openwrt_dhcp_odhcpd_loglevel: "4"
