---
- name: set kernel parameters for build
  ansible.builtin.lineinfile:
    path: "{{ openwrt_imagebuilder_builddir }}/{{ openwrt_imagebuilder_extractedfolder }}/.config"
    regexp: "^{{ item.name }}="
    line: "{{ item.name }}={{ item.value }}"
  loop: "{{ openwrt_imagebuilder_kernelvars }}"
  when: openwrt_imagebuilder_kernelvars is defined
- name: List packages that will be in the image
  debug:
    var: openwrt_packages_install
- name: List packages that will be remove in the image
  debug:
    var: openwrt_packages_remove
- name: Convert imagebuilder packages into list
  ansible.builtin.set_fact:
    openwrt_packages_imagebuilder: "{{ ( openwrt_packages_install + ( openwrt_packages_remove | map('regex_replace', '^', '-'))) | join(openwrt_packages_separator) }}"
  when: openwrt_packages_install is defined
- name: Building info
  debug:
    msg: "Building with the following command: make image PACKAGES={{ openwrt_packages_imagebuilder }} FILES={{ openwrt_imagebuilder_filesdir }}"
  when: openwrt_imagebuilder_profile is not defined
- name: Building info
  debug:
    msg: "Building with the following command: make image PACKAGES={{ openwrt_packages_imagebuilder }} FILES={{ openwrt_imagebuilder_filesdir }} PROFILE={{ openwrt_imagebuilder_profile }}"
  when: openwrt_imagebuilder_profile is defined
- name: Create image
  ansible.builtin.shell: make image PACKAGES="{{ openwrt_packages_imagebuilder|default("") }}" FILES="{{ openwrt_imagebuilder_filesdir }}"
  args:
    chdir: "{{ openwrt_imagebuilder_builddir }}/{{ openwrt_imagebuilder_extractedfolder }}"
  when: openwrt_imagebuilder_profile is not defined
- name: Create image with profile option
  ansible.builtin.shell: make image PACKAGES="{{ openwrt_packages_imagebuilder|default("") }}" FILES="{{ openwrt_imagebuilder_filesdir }}" PROFILE="{{ openwrt_imagebuilder_profile }}"
  args:
    chdir: "{{ openwrt_imagebuilder_builddir }}/{{ openwrt_imagebuilder_extractedfolder }}"
  when: openwrt_imagebuilder_profile is defined
- name: compress and remove for user set path
  community.general.archive:
    path: "{{ openwrt_imagebuilder_builddir }}/{{ openwrt_imagebuilder_extractedfolder }}/bin"
    dest: "{{ openwrt_imagebuilder_destinationpath }}/{{ inventory_hostname }}.tar.gz"
    remove: true
  when: openwrt_imagebuilder_destinationpath is defined
- name: compress images and remove
  community.general.archive:
    path: "{{ openwrt_imagebuilder_builddir }}/{{ openwrt_imagebuilder_extractedfolder }}/bin"
    dest: "{{ openwrt_imagebuilder_outputdir }}/{{ inventory_hostname }}.tar.gz"
    remove: true
  when: not openwrt_imagebuilder_destinationpath is defined
